# mvn clean install -DskipTests=true && podman-compose build --no-cache && podman-compose up
# mvn clean install -DskipTests=true && docker-compose build --no-cache && docker-compose up
version: '3'
services:
#   mongo-parking:
#     image: mongo
#     container_name: mongo-parking
#     ports:
#       - "27017:27017"
  
  parking-meter-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-meter-container
    ports:
      - "8080:8080"
