spring:
  application.name: ParkingMeterMonitor
  banner.location: static/banner.txt
  data:
    mongodb:
        uri: mongodb://localhost/parking-meter
        port: 27017
        username:
        password:
