spring:
    # profiles.active: local
    application.name: ParkingMeterMonitor
    banner.location: static/banner.txt
    data:
        mongodb:
            uri: mongodb://mongo-parking:27017/parking-meter
            username:
            password:
